[package]
name = "ws-protocol"
version = "0.0.2"
authors = ["SteveXMH <39523898+Steve-xmh@users.noreply.github.com>"]
edition = "2024"
repository = "https://github.com/Steve-xmh/applemusic-like-lyrics"
description = "一个歌词播放器协议库，用于不同播放软件与实现本协议的歌词播放器同步播放进度和播放信息"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
binrw = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_with = { version = "3.14", features = ["base64"] }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
serde_json = "1.0"
tungstenite = "0.27"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["console_error_panic_hook"]
tracing = ["dep:tracing"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
